model:
  base_model: "ProsusAI/finbert"
  output_dir: "data/finetuned_models/financial_llm"
  max_length: 512
  num_epochs: 5
  batch_size: 4
  gradient_accumulation_steps: 8
  learning_rate: 1e-5
  weight_decay: 0.01
  warmup_steps: 100
  training_args:
    output_dir: "data/finetuned_models/financial_llm"
    num_train_epochs: 5
    per_device_train_batch_size: 4
    per_device_eval_batch_size: 4
    gradient_accumulation_steps: 8
    learning_rate: 1e-5
    weight_decay: 0.01
    warmup_steps: 100
    logging_dir: "logs"
    logging_steps: 10
    evaluation_strategy: "steps"
    eval_steps: 50
    save_strategy: "steps"
    save_steps: 50
    load_best_model_at_end: true
    metric_for_best_model: "accuracy"
    greater_is_better: true
    fp16: false
    bf16: false
    optim: "adamw_torch"
    lr_scheduler_type: "linear"
    report_to: "none" 